create table if not exists public.products (
  id bigint generated by default as identity (start with 1000) primary key,
  date text not null,
  title text not null,
  client_information text not null,
  describe text not null,
  image_url text not null,
  partner_logo_url text,
  category text check (category in ('cartoon-3d', 'tvc', 'art')),
  video_url text,
  model_url text,
  image_gallery jsonb not null default '[]'::jsonb,
  video_gallery jsonb not null default '[]'::jsonb,
  quick_view_layout jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products
add column if not exists partner_logo_url text;

alter table public.products enable row level security;

grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;

drop policy if exists "Products are publicly readable" on public.products;
drop policy if exists "Authenticated admins can create products" on public.products;
drop policy if exists "Authenticated admins can update products" on public.products;
drop policy if exists "Authenticated admins can delete products" on public.products;

create policy "Products are publicly readable"
on public.products for select
to anon, authenticated
using (true);

create policy "Authenticated admins can create products"
on public.products for insert
to authenticated
with check (true);

create policy "Authenticated admins can update products"
on public.products for update
to authenticated
using (true)
with check (true);

create policy "Authenticated admins can delete products"
on public.products for delete
to authenticated
using (true);

create table if not exists public.site_content (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

grant select on public.site_content to anon, authenticated;
grant insert, update, delete on public.site_content to authenticated;

drop policy if exists "Site content is publicly readable" on public.site_content;
drop policy if exists "Authenticated admins can create site content" on public.site_content;
drop policy if exists "Authenticated admins can update site content" on public.site_content;
drop policy if exists "Authenticated admins can delete site content" on public.site_content;

create policy "Site content is publicly readable"
on public.site_content for select
to anon, authenticated
using (true);

create policy "Authenticated admins can create site content"
on public.site_content for insert
to authenticated
with check (true);

create policy "Authenticated admins can update site content"
on public.site_content for update
to authenticated
using (true)
with check (true);

create policy "Authenticated admins can delete site content"
on public.site_content for delete
to authenticated
using (true);

insert into storage.buckets (id, name, public)
values ('product-media', 'product-media', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can view product media" on storage.objects;
drop policy if exists "Authenticated admins can upload product media" on storage.objects;
drop policy if exists "Authenticated admins can update product media" on storage.objects;
drop policy if exists "Authenticated admins can delete product media" on storage.objects;

create policy "Public can view product media"
on storage.objects for select
to public
using (bucket_id = 'product-media');

create policy "Authenticated admins can upload product media"
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-media');

create policy "Authenticated admins can update product media"
on storage.objects for update
to authenticated
using (bucket_id = 'product-media')
with check (bucket_id = 'product-media');

create policy "Authenticated admins can delete product media"
on storage.objects for delete
to authenticated
using (bucket_id = 'product-media');
