create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  logo_url text not null,
  description text,
  website_url text,
  display_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity (start with 1000) primary key,
  date text not null,
  title text not null,
  describe text not null,
  image_url text not null,
  brand_id bigint not null references public.brands(id) on delete restrict,
  category text check (category in ('cartoon-3d', 'tvc', 'art', 'showreel')),
  video_url text,
  model_url text,
  image_gallery jsonb not null default '[]'::jsonb,
  video_gallery jsonb not null default '[]'::jsonb,
  quick_view_layout jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products
drop constraint if exists products_category_check;

alter table public.products
add constraint products_category_check
check (category in ('cartoon-3d', 'tvc', 'art', 'showreel'));

alter table public.products enable row level security;

grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;

drop policy if exists "Products are publicly readable" on public.products;
drop policy if exists "Authenticated admins can create products" on public.products;
drop policy if exists "Authenticated admins can update products" on public.products;
drop policy if exists "Authenticated admins can delete products" on public.products;

create policy "Products are publicly readable"
on public.products for select
to anon, authenticated
using (true);

create policy "Authenticated admins can create products"
on public.products for insert
to authenticated
with check (true);

create policy "Authenticated admins can update products"
on public.products for update
to authenticated
using (true)
with check (true);

create policy "Authenticated admins can delete products"
on public.products for delete
to authenticated
using (true);

create table if not exists public.site_content (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

grant select on public.site_content to anon, authenticated;
grant insert, update, delete on public.site_content to authenticated;

drop policy if exists "Site content is publicly readable" on public.site_content;
drop policy if exists "Authenticated admins can create site content" on public.site_content;
drop policy if exists "Authenticated admins can update site content" on public.site_content;
drop policy if exists "Authenticated admins can delete site content" on public.site_content;

create policy "Site content is publicly readable"
on public.site_content for select
to anon, authenticated
using (true);

create policy "Authenticated admins can create site content"
on public.site_content for insert
to authenticated
with check (true);

create policy "Authenticated admins can update site content"
on public.site_content for update
to authenticated
using (true)
with check (true);

create policy "Authenticated admins can delete site content"
on public.site_content for delete
to authenticated
using (true);

insert into storage.buckets (id, name, public)
values ('product-media', 'product-media', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can view product media" on storage.objects;
drop policy if exists "Authenticated admins can upload product media" on storage.objects;
drop policy if exists "Authenticated admins can update product media" on storage.objects;
drop policy if exists "Authenticated admins can delete product media" on storage.objects;

create policy "Public can view product media"
on storage.objects for select
to public
using (bucket_id = 'product-media');

create policy "Authenticated admins can upload product media"
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-media');

create policy "Authenticated admins can update product media"
on storage.objects for update
to authenticated
using (bucket_id = 'product-media')
with check (bucket_id = 'product-media');

create policy "Authenticated admins can delete product media"
on storage.objects for delete
to authenticated
using (bucket_id = 'product-media');

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  image text not null,
  color text not null default 'rgba(255, 255, 255, 0.15)',
  bio text not null,
  socials jsonb not null default '{}'::jsonb,
  skills jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint members_socials_is_object check (jsonb_typeof(socials) = 'object'),
  constraint members_skills_is_array check (jsonb_typeof(skills) = 'array')
);

alter table public.members enable row level security;

grant select on public.members to anon, authenticated;
grant insert, update, delete on public.members to authenticated;
grant usage, select on sequence public.members_id_seq to authenticated;

drop policy if exists "Members are publicly readable" on public.members;
drop policy if exists "Authenticated admins can create members" on public.members;
drop policy if exists "Authenticated admins can update members" on public.members;
drop policy if exists "Authenticated admins can delete members" on public.members;

create policy "Members are publicly readable"
on public.members for select
to anon, authenticated
using (true);

create policy "Authenticated admins can create members"
on public.members for insert
to authenticated
with check (true);

create policy "Authenticated admins can update members"
on public.members for update
to authenticated
using (true)
with check (true);

create policy "Authenticated admins can delete members"
on public.members for delete
to authenticated
using (true);

-- Backend-only mutation security. The Express API uses service_role after it
-- verifies the caller against admin_users (or a server-side allowlist).
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
revoke all on public.admin_users from anon, authenticated;
revoke insert, update, delete on public.products from authenticated;
revoke insert, update, delete on public.site_content from authenticated;
revoke insert, update, delete on public.members from authenticated;
revoke usage on sequence public.products_id_seq from authenticated;
revoke usage on sequence public.members_id_seq from authenticated;

drop policy if exists "Authenticated admins can create products" on public.products;
drop policy if exists "Authenticated admins can update products" on public.products;
drop policy if exists "Authenticated admins can delete products" on public.products;
drop policy if exists "Authenticated admins can create site content" on public.site_content;
drop policy if exists "Authenticated admins can update site content" on public.site_content;
drop policy if exists "Authenticated admins can delete site content" on public.site_content;
drop policy if exists "Authenticated admins can create members" on public.members;
drop policy if exists "Authenticated admins can update members" on public.members;
drop policy if exists "Authenticated admins can delete members" on public.members;
drop policy if exists "Authenticated admins can upload product media" on storage.objects;
drop policy if exists "Authenticated admins can update product media" on storage.objects;
drop policy if exists "Authenticated admins can delete product media" on storage.objects;

alter table public.products
add column if not exists brand_id bigint references public.brands(id) on delete set null;

create index if not exists products_brand_id_idx on public.products(brand_id);
alter table public.brands enable row level security;
grant select on public.brands to anon, authenticated;
revoke insert, update, delete on public.brands from anon, authenticated;
revoke usage on sequence public.brands_id_seq from anon, authenticated;

drop policy if exists "Brands are publicly readable" on public.brands;
create policy "Brands are publicly readable"
on public.brands for select
to anon, authenticated
using (is_visible = true);

insert into storage.buckets (id, name, public)
values ('brand-assets', 'brand-assets', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can view brand assets" on storage.objects;
create policy "Public can view brand assets"
on storage.objects for select
to public
using (bucket_id = 'brand-assets');

insert into public.brands (
  name,
  slug,
  logo_url,
  description,
  website_url,
  display_order,
  is_visible
)
values (
  'Future Studio',
  'future-studio',
  'https://futurestudiovn.com/images/logofuturesymbol.png',
  'Future Studio internal production.',
  'https://futurestudiovn.com',
  10000,
  false
)
on conflict (slug) do nothing;

-- Products reference brands for all client names and logos.
-- Keep this block after the brands table is created.
alter table public.products
drop constraint if exists products_brand_id_fkey;

alter table public.products
alter column brand_id set not null;

alter table public.products
add constraint products_brand_id_fkey
foreign key (brand_id)
references public.brands(id)
on delete restrict;

alter table public.products
drop column if exists client_information,
drop column if exists partner_logo_url;
