-- Brand directory and product relationships. Public data is read by Express;
-- every mutation remains restricted to the service-role backend.
create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  logo_url text not null,
  description text,
  website_url text,
  display_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products
add column if not exists brand_id bigint references public.brands(id) on delete set null;

create index if not exists products_brand_id_idx on public.products(brand_id);

alter table public.brands enable row level security;
grant select on public.brands to anon, authenticated;
revoke insert, update, delete on public.brands from anon, authenticated;
revoke usage on sequence public.brands_id_seq from anon, authenticated;

drop policy if exists "Brands are publicly readable" on public.brands;
create policy "Brands are publicly readable"
on public.brands for select
to anon, authenticated
using (is_visible = true);

insert into storage.buckets (id, name, public)
values ('brand-assets', 'brand-assets', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can view brand assets" on storage.objects;
drop policy if exists "Authenticated admins can upload brand assets" on storage.objects;
drop policy if exists "Authenticated admins can update brand assets" on storage.objects;
drop policy if exists "Authenticated admins can delete brand assets" on storage.objects;

create policy "Public can view brand assets"
on storage.objects for select
to public
using (bucket_id = 'brand-assets');
