create table if not exists public.members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  image text not null,
  color text not null default 'rgba(255, 255, 255, 0.15)',
  bio text not null,
  socials jsonb not null default '{}'::jsonb,
  skills jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint members_socials_is_object check (jsonb_typeof(socials) = 'object'),
  constraint members_skills_is_array check (jsonb_typeof(skills) = 'array')
);

alter table public.members enable row level security;

grant select on public.members to anon, authenticated;
grant insert, update, delete on public.members to authenticated;
grant usage, select on sequence public.members_id_seq to authenticated;

drop policy if exists "Members are publicly readable" on public.members;
drop policy if exists "Authenticated admins can create members" on public.members;
drop policy if exists "Authenticated admins can update members" on public.members;
drop policy if exists "Authenticated admins can delete members" on public.members;

create policy "Members are publicly readable"
on public.members for select
to anon, authenticated
using (true);

create policy "Authenticated admins can create members"
on public.members for insert
to authenticated
with check (true);

create policy "Authenticated admins can update members"
on public.members for update
to authenticated
using (true)
with check (true);

create policy "Authenticated admins can delete members"
on public.members for delete
to authenticated
using (true);

insert into public.members (id, name, role, image, color, bio, socials, skills)
values
  (
    1,
    'Trần Tiến Đạt',
    'BOSS & Founder',
    'images/anhdat.jpg',
    'rgba(255, 255, 255, 0.15)',
    'Thiết kế không chỉ là tạo ra cái đẹp, mà là nghệ thuật kể câu chuyện của thương hiệu bằng ngôn ngữ thị giác.',
    '{"github":"#","linkedin":"#"}'::jsonb,
    '[]'::jsonb
  ),
  (
    2,
    'Lê Chí Cường',
    '3D Artist',
    'images/anhcuong.jpg',
    'rgba(255, 255, 255, 0.15)',
    'Đưa ý tưởng của bạn bước ra ngoài mặt giấy.',
    '{"behance":"#","dribbble":"#"}'::jsonb,
    '[]'::jsonb
  ),
  (
    3,
    'Hoàng Thị Trà My',
    'Lighting Artist',
    'images/anhTraMy.jpg',
    'rgba(255, 255, 255, 0.15)',
    'Nơi ánh sáng làm chủ khung hình và bóng tối kể những câu chuyện bí ẩn.',
    '{"behance":"#","dribbble":"#"}'::jsonb,
    '[]'::jsonb
  ),
  (
    4,
    'Thiều Sinh Tuấn',
    '2D Artist',
    'images/anhSinhTuan.jpg',
    'rgba(255, 255, 255, 0.15)',
    'Mỗi nét vẽ là một nhịp đập của tâm hồn, nơi màu sắc và hình khối hòa quyện để tạo nên những tác phẩm sống động.',
    '{"behance":"#","dribbble":"#"}'::jsonb,
    '[]'::jsonb
  ),
  (
    5,
    'Nguyễn Hà Vi',
    '2D Artist',
    'images/rem.jpg',
    'rgba(255, 255, 255, 0.15)',
    'Sáng tạo không giới hạn. Vẽ nên mọi ý tưởng.',
    '{"behance":"#","dribbble":"#"}'::jsonb,
    '[]'::jsonb
  )
on conflict (id)
do update set
  name = excluded.name,
  role = excluded.role,
  image = excluded.image,
  color = excluded.color,
  bio = excluded.bio,
  socials = excluded.socials,
  skills = excluded.skills,
  updated_at = now();

select setval(
  pg_get_serial_sequence('public.members', 'id'),
  coalesce((select max(id) from public.members), 1),
  true
);
